export default function useCards() {
    const cards = [
        { img: "b", src: "/sources/cards/back.svg" },
        { img: "6s", src: "/sources/cards/6_of_spades.svg" },
        { img: "ac", src: "/sources/cards/ace_of_clubs.svg" },
        { img: "kc", src: "/sources/cards/king_of_clubs.svg" },
        { img: "bj", src: "/sources/cards/black_joker.svg" },
        { img: "jh", src: "/sources/cards/jack_of_hearts.svg" },
        { img: "rj", src: "/sources/cards/red_joker.svg" },
        { img: "kh", src: "/sources/cards/king_of_hearts.svg" },
        { img: "qh", src: "/sources/cards/queen_of_hearts.svg" },
        { img: "9h", src: "/sources/cards/9_of_hearts.svg" },
        { img: "4c", src: "/sources/cards/4_of_clubs.svg" },
        { img: "8h", src: "/sources/cards/8_of_hearts.svg" },
        { img: "qc", src: "/sources/cards/queen_of_clubs.svg" },
        { img: "7s", src: "/sources/cards/7_of_spades.svg" },
        { img: "5d", src: "/sources/cards/5_of_diamonds.svg" },
        { img: "ad", src: "/sources/cards/ace_of_diamonds.svg" },
        { img: "2s", src: "/sources/cards/2_of_spades.svg" },
        { img: "qs", src: "/sources/cards/queen_of_spades.svg" },
        { img: "7h", src: "/sources/cards/7_of_hearts.svg" },
        { img: "1d", src: "/sources/cards/10_of_diamonds.svg" },
        { img: "2h", src: "/sources/cards/2_of_hearts.svg" },
        { img: "qd", src: "/sources/cards/queen_of_diamonds.svg" },
        { img: "6h", src: "/sources/cards/6_of_hearts.svg" },
        { img: "2c", src: "/sources/cards/2_of_clubs.svg" },
        { img: "kd", src: "/sources/cards/king_of_diamonds.svg" },
        { img: "ah", src: "/sources/cards/ace_of_hearts.svg" },
        { img: "3d", src: "/sources/cards/3_of_diamonds.svg" },
        { img: "3c", src: "/sources/cards/3_of_clubs.svg" },
        { img: "9s", src: "/sources/cards/9_of_spades.svg" },
        { img: "jc", src: "/sources/cards/jack_of_clubs.svg" },
        { img: "9c", src: "/sources/cards/9_of_clubs.svg" },
        { img: "9d", src: "/sources/cards/9_of_diamonds.svg" },
        { img: "2d", src: "/sources/cards/2_of_diamonds.svg" },
        { img: "8s", src: "/sources/cards/8_of_spades.svg" },
        { img: "5h", src: "/sources/cards/5_of_hearts.svg" },
        { img: "8d", src: "/sources/cards/8_of_diamonds.svg" },
        { img: "js", src: "/sources/cards/jack_of_spades.svg" },
        { img: "1c", src: "/sources/cards/10_of_clubs.svg" },
        { img: "4s", src: "/sources/cards/4_of_spades.svg" },
        { img: "as", src: "/sources/cards/ace_of_spades.svg" },
        { img: "5s", src: "/sources/cards/5_of_spades.svg" },
        { img: "3s", src: "/sources/cards/3_of_spades.svg" },
        { img: "6d", src: "/sources/cards/6_of_diamonds.svg" },
        { img: "7d", src: "/sources/cards/7_of_diamonds.svg" },
        { img: "3h", src: "/sources/cards/3_of_hearts.svg" },
        { img: "4d", src: "/sources/cards/4_of_diamonds.svg" },
        { img: "ks", src: "/sources/cards/king_of_spades.svg" },
        { img: "1h", src: "/sources/cards/10_of_hearts.svg" },
        { img: "5c", src: "/sources/cards/5_of_clubs.svg" },
        { img: "4h", src: "/sources/cards/4_of_hearts.svg" },
        { img: "8c", src: "/sources/cards/8_of_clubs.svg" },
        { img: "1s", src: "/sources/cards/10_of_spades.svg" },
        { img: "6c", src: "/sources/cards/6_of_clubs.svg" },
        { img: "7c", src: "/sources/cards/7_of_clubs.svg" },
        { img: "jd", src: "/sources/cards/jack_of_diamonds.svg" }
    ];

    return {
        $cards: cards
    };
}
